name: Rust CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Build Docker image
      run: docker build -t rust-tests .  

    - name: Run tests
      run: docker run rust-tests
