name: Rust Docker Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Build Docker image
      run: docker build -t rust_app_test .

    - name: Run tests in Docker container
      run: docker run --rm rust_app_test
